[tool.poetry]
name = "reutly-app"
version = "0.1.0"
description = ""
authors = ["Kevin Cifuentes <kevins_cifuentes@soy.sena.edu.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
